name: My Workflow
on:
  push:
    tags: '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: prereqs
        uses: ConorMacBride/install-package@v1
        with:
          apt:  gcc automake autoconf zlib1g-dev  libcurl4-openssl-dev libcurl4 libssl3 make git autoconf-archive
      - name: Checkout code
        uses: actions/checkout@v4
      - name: build
        run: ./build.sh
      - name: test
        run: ./cpuminer --cputest
      - name: artifact
        run: tar -zcf release.tgz cpuminer
      - name: github-release
        uses: ncipollo/release-action@v1
        with: 
          artifacts: release.tgz

